import type { BlogPost } from "./types"

export const SAMPLE_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Огляд UX презентацій",
    description: "Як створювати переконливі презентації, які вражають ваших колег та керівників?",
    category: "design",
    image: "/blog/ux-presentations.jpg",
    author: {
      name: "Олена Рибак",
      avatar: "/avatars/olena-rybak.jpg",
    },
    date: "20 січня 2024",
  },
    {
      id: 2,
      title: "Міграція на Linear 101",
      description: "Linear допомагає оптимізувати проекти, спринти та відстеження помилок. Ось як почати.",
      category: "product",
      image: "/blog/linear-migration.jpg",
      author: {
        name: "Петро Бакер",
        avatar: "/avatars/petro-baker.jpg",
      },
      date: "19 січня 2024",
    },
    {
      id: 3,
      title: "Створення API стеку",
      description: "Зростання RESTful API супроводжується появою інструментів для їх створення та тестування.",
      category: "engineering",
      image: "/blog/api-stack.jpg",
      author: {
        name: "Лана Штейнер",
        avatar: "/avatars/lana-steiner.jpg",
      },
      date: "18 січня 2024",
    },
    {
      id: 4,
      title: "Основи веб-дизайну",
      description: "Вивчіть основні принципи сучасного веб-дизайну та створення користувацьких інтерфейсів.",
      category: "design",
      image: "/blog/web-design-basics.jpg",
      author: {
        name: "Марія Ковальчук",
        avatar: "/avatars/maria-kovalchuk.jpg",
      },
      date: "17 січня 2024",
    },
    {
      id: 5,
      title: "Agile методології",
      description: "Глибокий огляд Agile методологій та їх застосування в сучасній розробці програмного забезпечення.",
      category: "product",
      image: "/blog/agile-methods.jpg",
      author: {
        name: "Іван Петренко",
        avatar: "/avatars/ivan-petrenko.jpg",
      },
      date: "16 січня 2024",
    },
    {
      id: 6,
      title: "DevOps практики",
      description: "Найкращі практики DevOps для оптимізації процесу розробки та розгортання.",
      category: "engineering",
      image: "/blog/devops-practices.jpg",
      author: {
        name: "Андрій Мороз",
        avatar: "/avatars/andriy-moroz.jpg",
      },
      date: "15 січня 2024",
    },
    {
      id: 7,
      title: "Клієнтський сервіс",
      description: "Як побудувати відмінний клієнтський сервіс та підтримувати високий рівень задоволеності.",
      category: "customer",
      image: "/blog/customer-service.jpg",
      author: {
        name: "Софія Литвин",
        avatar: "/avatars/sofia-lytvyn.jpg",
      },
      date: "14 січня 2024",
    },
    {
      id: 8,
      title: "Тренди UI/UX 2024",
      description: "Огляд головних трендів у дизайні інтерфейсів та користувацькому досвіді на 2024 рік.",
      category: "design",
      image: "/blog/ui-ux-trends-2024.jpg",
      author: {
        name: "Дарина Шевченко",
        avatar: "/avatars/daryna-shevchenko.jpg",
      },
      date: "13 січня 2024",
    },
    {
      id: 9,
      title: "Штучний інтелект в бізнесі",
      description: "Як компанії використовують ШІ для оптимізації процесів та покращення обслуговування клієнтів.",
      category: "product",
      image: "/blog/ai-in-business.jpg",
      author: {
        name: "Максим Коваль",
        avatar: "/avatars/maxym-koval.jpg",
      },
      date: "12 січня 2024",
    },
    {
      id: 10,
      title: "Кібербезпека 2024",
      description: "Основні загрози та методи захисту в сучасному цифровому світі.",
      category: "engineering",
      image: "/blog/cybersecurity-2024.jpg",
      author: {
        name: "Віктор Мельник",
        avatar: "/avatars/viktor-melnyk.jpg",
      },
      date: "11 січня 2024",
    },
    {
      id: 11,
      title: "Дизайн-системи",
      description: "Створення та впровадження ефективних дизайн-систем для великих проектів.",
      category: "design",
      image: "/blog/design-systems.jpg",
      author: {
        name: "Анна Павленко",
        avatar: "/avatars/anna-pavlenko.jpg",
      },
      date: "10 січня 2024",
    },
    {
      id: 12,
      title: "Управління командою",
      description: "Стратегії ефективного управління віддаленими командами розробників.",
      category: "product",
      image: "/blog/team-management.jpg",
      author: {
        name: "Роман Сидоренко",
        avatar: "/avatars/roman-sydorenko.jpg",
      },
      date: "9 січня 2024",
    },
    {
      id: 13,
      title: "Мобільна розробка",
      description: "Тренди та найкращі практики розробки мобільних додатків у 2024 році.",
      category: "engineering",
      image: "/blog/mobile-development.jpg",
      author: {
        name: "Ірина Козак",
        avatar: "/avatars/iryna-kozak.jpg",
      },
      date: "8 січня 2024",
    },
    {
      id: 14,
      title: "Оптимізація конверсії",
      description: "Методи та інструменти для підвищення конверсії веб-сайтів.",
      category: "design",
      image: "/blog/conversion-optimization.jpg",
      author: {
        name: "Олег Василенко",
        avatar: "/avatars/oleg-vasylenko.jpg",
      },
      date: "7 січня 2024",
    },
    {
      id: 15,
      title: "Технічна підтримка",
      description: "Організація ефективної технічної підтримки для складних проектів.",
      category: "customer",
      image: "/blog/technical-support.jpg",
      author: {
        name: "Наталія Дубова",
        avatar: "/avatars/natalia-dubova.jpg",
      },
      date: "6 січня 2024",
    },
    {
      id: 16,
      title: "Продуктова аналітика",
      description: "Використання даних для прийняття продуктових рішень.",
      category: "product",
      image: "/blog/product-analytics.jpg",
      author: {
        name: "Андрій Зінченко",
        avatar: "/avatars/andriy-zinchenko.jpg",
      },
      date: "5 січня 2024",
    },
] 